import os
import glob
import re
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

# ==============================================================================
# CONFIGURATION
# ==============================================================================
BASENAME = "sim-x"         # Snapshot prefix ("sim-x" or "sim-y")
FIXED_AXIS = "X"           # Fixed plane coordinate ('X' or 'Y')
FIXED_COORD_VAL = 99       # Slice plane index: sim-x is (SizeX-1)/2,
                           # sim-y is SizeY/2 -- see snapshot3d.c
FIELD_NAME = "$E_x$"       # Field component recorded by snapshot3d
FRAME_INTERVAL_MS = 300    # Playback speed (milliseconds per frame)
DYNAMIC_AUTOSCALE = True   # Rescale color limits based on peak field value
COLORMAP = "RdBu_r"        # Red = positive, Blue = negative
VMIN, VMAX = -0.7, 0.7     # Static color limits (if DYNAMIC_AUTOSCALE = False)
# ==============================================================================


def load_frame(filename):
    """Reads a binary raw snapshot frame file generated by snapshot3d."""
    with open(filename, 'rb') as f:
        # First 2 floats store dimensions (dim1, dim2)
        header = np.fromfile(f, dtype=np.float32, count=2)
        if len(header) < 2:
            return None, 0, 0
        dim1, dim2 = int(header[0]), int(header[1])
        
        # Read field array
        data = np.fromfile(f, dtype=np.float32)
        
        # Reshape into 2D grid (dim2 rows = Z, dim1 cols = X or Y)
        field = data.reshape((dim2, dim1))

        # snapshot3d writes rows from pp = SizeZ-1 down to 0, so the first row
        # is the TOP of the grid. Flip it so origin='lower' puts Z=0 at the
        # bottom. Without this the Z axis is rendered upside-down (invisible on
        # a symmetric dipole, wrong as soon as the grid is not Z-symmetric).
        field = np.flipud(field)

        return field, dim1, dim2


def main():
    # Set dynamic axis labels based on the chosen fixed plane
    if FIXED_AXIS.upper() == "X":
        horiz_label = "Y Node Index"
        vert_label = "Z Node Index"
        plane_title = f"{FIELD_NAME} Slice at {FIXED_AXIS} = {FIXED_COORD_VAL}"
    else:
        horiz_label = "X Node Index"
        vert_label = "Z Node Index"
        plane_title = f"{FIELD_NAME} Slice at {FIXED_AXIS} = {FIXED_COORD_VAL}"

    # Find all snapshot files matching 'BASENAME.<number>'
    pattern = re.compile(rf"^{re.escape(BASENAME)}\.(\d+)$")
    file_tuples = []
    for f in os.listdir('.'):
        match = pattern.match(f)
        if match:
            file_tuples.append((int(match.group(1)), f))
            
    if not file_tuples:
        print(f"No snapshot files found matching prefix '{BASENAME}.<number>'")
        return
        
    # Sort files in numerical order (.0, .1, .2, ...)
    file_tuples.sort(key=lambda x: x[0])
    files = [t[1] for t in file_tuples]
    
    print(f"Found {len(files)} frames for {plane_title}. Displaying animation...")
    
    # Read initial frame
    first_field, n_horiz, n_vert = load_frame(files[0])
    
    fig, ax = plt.subplots(figsize=(8, 6))
    
    im = ax.imshow(
        first_field, 
        cmap=COLORMAP, 
        origin='lower',  # Fits standard coordinate orientation
        extent=[0, n_horiz - 1, 0, n_vert - 1],
        vmin=VMIN, 
        vmax=VMAX
    )
    
    cbar = fig.colorbar(im, ax=ax)
    cbar.set_label(f'{FIELD_NAME} Field Amplitude', rotation=270, labelpad=15)
    
    title_text = ax.set_title(f"{plane_title} | Frame 0/{len(files)-1} ({files[0]})")
    ax.set_xlabel(horiz_label)
    ax.set_ylabel(vert_label)
    
    def update(frame_idx):
        fname = files[frame_idx]
        field, _, _ = load_frame(fname)
        if field is not None:
            im.set_array(field)
            
            if DYNAMIC_AUTOSCALE:
                max_val = np.max(np.abs(field))
                if max_val > 1e-6:
                    im.set_clim(vmin=-max_val, vmax=max_val)
                
            title_text.set_text(f"{plane_title} | Frame {frame_idx}/{len(files)-1} ({fname})")
        return [im, title_text]

    anim = FuncAnimation(
        fig, 
        update, 
        frames=len(files), 
        interval=FRAME_INTERVAL_MS, 
        blit=False
    )
    
    plt.tight_layout()
    plt.show()


if __name__ == '__main__':
    main()