import os
import glob
import re
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

# ==============================================================================
# CONFIGURATION
# ==============================================================================
# GIF Export Configuration
SAVE_GIF     = True                        # Set to True to save animation as a GIF file
GIF_FILENAME = "images/fdtd_simulation.gif"  # Output GIF filename
GIF_FPS      = 10                            # Frames per second for playback
GIF_DPI      = 100                           # Resolution

# Fixed Colorbar Bounds (Prevents dynamic autoscaling artifacts)
COLOR_MIN = -0.2
COLOR_MAX = 0.2

PLAYBACK_INTERVAL = 300  # ms per frame (0.3s)
# ==============================================================================

def load_frame(filename):
    """Reads a binary raw snapshot frame file generated by snapshot2d."""
    with open(filename, 'rb') as f:
        header = np.fromfile(f, dtype=np.float32, count=2)
        if len(header) < 2:
            return None, 0, 0
        nx, ny = int(header[0]), int(header[1])
        
        data = np.fromfile(f, dtype=np.float32)
        field = data.reshape((ny, nx))
        
        # FLIP VERTICALLY: Realigns raw row-major binary data to standard Cartesian Y=0 bottom layout
        field = np.flipud(field)
        
        return field, nx, ny

def main():
    basename = "sim"
    pattern = re.compile(rf"^{re.escape(basename)}\.(\d+)$")
    file_tuples = []
    
    for f in os.listdir('.'):
        match = pattern.match(f)
        if match:
            file_tuples.append((int(match.group(1)), f))
            
    if not file_tuples:
        print(f"No snapshot files found with prefix '{basename}.'")
        return
        
    file_tuples.sort(key=lambda x: x[0])
    files = [t[1] for t in file_tuples]
    
    print(f"Found {len(files)} frames. Preparing animation...")
    first_field, nx, ny = load_frame(files[0])
    
    fig, ax = plt.subplots(figsize=(8, 6))
    
    # Render raw Ez field heatmap
    im = ax.imshow(
        first_field, 
        cmap='RdBu_r', 
        origin='lower',
        extent=[-0.5, nx - 0.5, -0.5, ny - 0.5],
        vmin=COLOR_MIN, 
        vmax=COLOR_MAX
    )

    cbar = fig.colorbar(im, ax=ax)
    cbar.set_label('$E_z$ Field Amplitude', rotation=270, labelpad=15)
    
    title_text = ax.set_title(f"Frame 0 / {len(files)-1} ({files[0]})")
    ax.set_xlabel("X Node Index")
    ax.set_ylabel("Y Node Index")
    
    def update(frame_idx):
        fname = files[frame_idx]
        field, _, _ = load_frame(fname)
        if field is not None:
            im.set_array(field)
            im.set_clim(vmin=COLOR_MIN, vmax=COLOR_MAX)
            title_text.set_text(f"Frame {frame_idx} / {len(files)-1} ({fname})")
        return [im, title_text]

    anim = FuncAnimation(
        fig, 
        update, 
        frames=len(files), 
        interval=PLAYBACK_INTERVAL, 
        blit=False
    )
    
    plt.tight_layout()

    # Save clean GIF output
    if SAVE_GIF:
        out_dir = os.path.dirname(GIF_FILENAME)
        if out_dir:
            os.makedirs(out_dir, exist_ok=True)
            
        print(f"Saving animation to '{GIF_FILENAME}'...")
        anim.save(GIF_FILENAME, writer='pillow', fps=GIF_FPS, dpi=GIF_DPI)
        print("GIF export complete!")

    plt.show()

if __name__ == '__main__':
    main()