import os
import glob
import re
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from matplotlib.animation import FuncAnimation

# ==============================================================================
# CONFIGURATION & OVERLAY TOGGLES
# ==============================================================================
SHOW_TFSF = True       # Toggle TFSF boundary rectangle
SHOW_PEC  = True       # Toggle PEC plate line

# GIF Export Configuration
SAVE_GIF     = False                  # Set to True to save animation as a GIF file
GIF_FILENAME = "images/fdtd_simulation.gif"  # Output GIF filename
GIF_FPS      = 10                    # Frames per second for playback
GIF_DPI      = 100                   # Resolution (100 is standard for web/GitHub)

# Fixed Colorbar Bounds (Prevents zooming into 0.0001 numerical noise)
COLOR_MIN = -0.5
COLOR_MAX = 0.5

# Exact C grid coordinates from config.h
TF_FIRST_NODE_X = 40
TF_FIRST_NODE_Y = 25
TF_LAST_NODE_X  = 75
TF_LAST_NODE_Y  = 66

# PEC Plate: Center X = (40 + 75) / 2 = 57, Y spans from 30 to 61 (5-cell margin)
PEC_X = (TF_FIRST_NODE_X + TF_LAST_NODE_X) // 2
PEC_MARGIN_Y = 5
PEC_Y_MIN = TF_FIRST_NODE_Y + PEC_MARGIN_Y
PEC_Y_MAX = TF_LAST_NODE_Y - PEC_MARGIN_Y

PLAYBACK_INTERVAL = 300  # ms per frame (0.3s)
# ==============================================================================

def load_frame(filename):
    """Reads a binary raw snapshot frame file generated by snapshot2d."""
    with open(filename, 'rb') as f:
        header = np.fromfile(f, dtype=np.float32, count=2)
        if len(header) < 2:
            return None, 0, 0
        nx, ny = int(header[0]), int(header[1])
        
        data = np.fromfile(f, dtype=np.float32)
        field = data.reshape((ny, nx))
        
        # FLIP VERTICALLY: Realigns raw row-major binary data to standard Cartesian Y=0 bottom layout
        field = np.flipud(field)
        
        return field, nx, ny

def main():
    basename = "sim"
    pattern = re.compile(rf"^{re.escape(basename)}\.(\d+)$")
    file_tuples = []
    
    for f in os.listdir('.'):
        match = pattern.match(f)
        if match:
            file_tuples.append((int(match.group(1)), f))
            
    if not file_tuples:
        print(f"No snapshot files found with prefix '{basename}.'")
        return
        
    file_tuples.sort(key=lambda x: x[0])
    files = [t[1] for t in file_tuples]
    
    print(f"Found {len(files)} frames. Preparing animation...")
    first_field, nx, ny = load_frame(files[0])
    
    fig, ax = plt.subplots(figsize=(8, 6))
    
    # Render with origin='lower' on vertically flipped array
    # Extent uses [-0.5, N-0.5] to center pixel cells precisely on integer grid coordinates
    im = ax.imshow(
        first_field, 
        cmap='RdBu_r', 
        origin='lower',
        extent=[-0.5, nx - 0.5, -0.5, ny - 0.5],
        vmin=COLOR_MIN, 
        vmax=COLOR_MAX
    )
    
    # --------------------------------------------------------------------------
    # DRAW OVERLAYS
    # --------------------------------------------------------------------------
    if SHOW_TFSF:
        # Include boundary nodes inclusively (+1 to prevent 1-pixel leakage)
        width = (TF_LAST_NODE_X - TF_FIRST_NODE_X) + 1
        height = (TF_LAST_NODE_Y - TF_FIRST_NODE_Y) + 1
        
        # Anchor at lower-left node with -0.5 pixel-centering offset
        tf_rect = Rectangle(
            (TF_FIRST_NODE_X - 0.5, TF_FIRST_NODE_Y - 0.5), 
            width, 
            height,
            fill=False,
            edgecolor='black',
            linewidth=2.0,
            linestyle='--',
            label='TFSF Boundary'
        )
        ax.add_patch(tf_rect)

    if SHOW_PEC:
        ax.plot(
            [PEC_X, PEC_X], [PEC_Y_MIN, PEC_Y_MAX], 
            color='black', 
            linewidth=3.0, 
            linestyle='-', 
            label='PEC Plate'
        )

    if SHOW_TFSF or SHOW_PEC:
        ax.legend(loc='upper right', framealpha=0.9)

    # --------------------------------------------------------------------------
    cbar = fig.colorbar(im, ax=ax)
    cbar.set_label('$E_z$ Field Amplitude', rotation=270, labelpad=15)
    
    title_text = ax.set_title(f"Frame 0 / {len(files)-1} ({files[0]})")
    ax.set_xlabel("X Node Index")
    ax.set_ylabel("Y Node Index")
    
    def update(frame_idx):
        fname = files[frame_idx]
        field, _, _ = load_frame(fname)
        if field is not None:
            im.set_array(field)
            
            # FIXED COLOR LIMITS: Keeps field amplitudes grounded to absolute scale [-0.5, 0.5]
            im.set_clim(vmin=COLOR_MIN, vmax=COLOR_MAX)
                
            title_text.set_text(f"Frame {frame_idx} / {len(files)-1} ({fname})")
        return [im, title_text]

    anim = FuncAnimation(
        fig, 
        update, 
        frames=len(files), 
        interval=PLAYBACK_INTERVAL, 
        blit=False
    )
    
    plt.tight_layout()

    # --------------------------------------------------------------------------
    # OPTIONAL GIF EXPORT
    # --------------------------------------------------------------------------
    if SAVE_GIF:
        print(f"Saving animation to '{GIF_FILENAME}'...")
        anim.save(GIF_FILENAME, writer='pillow', fps=GIF_FPS, dpi=GIF_DPI)
        print("GIF export complete!")

    plt.show()

if __name__ == '__main__':
    main()