import os
import glob
import re
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

def load_frame(filename):
    """Reads a binary raw snapshot frame file generated by snapshot2d."""
    with open(filename, 'rb') as f:
        # First 2 floats store dimensions (Nx, Ny)
        header = np.fromfile(f, dtype=np.float32, count=2)
        if len(header) < 2:
            return None, 0, 0
        nx, ny = int(header[0]), int(header[1])
        
        # Read Ez field array
        data = np.fromfile(f, dtype=np.float32)
        
        # Reshape into 2D grid (Ny rows, Nx columns)
        field = data.reshape((ny, nx))
        return field, nx, ny

def main():
    basename = "sim"
    
    # Find all snapshot files matching 'sim.<number>'
    pattern = re.compile(rf"^{re.escape(basename)}\.(\d+)$")
    file_tuples = []
    for f in os.listdir('.'):
        match = pattern.match(f)
        if match:
            file_tuples.append((int(match.group(1)), f))
            
    if not file_tuples:
        print(f"No snapshot files found with prefix '{basename}.'")
        return
        
    # Sort files in correct numerical order (sim.0, sim.1, sim.2, ...)
    file_tuples.sort(key=lambda x: x[0])
    files = [t[1] for t in file_tuples]
    
    print(f"Found {len(files)} frames. Displaying animation...")
    
    # Read initial frame to get dimensions
    first_field, nx, ny = load_frame(files[0])
    
    fig, ax = plt.subplots(figsize=(8, 6))
    
    # Set up colormap (RdBu_r: Red = positive Ez, Blue = negative Ez)
    im = ax.imshow(
        first_field, 
        cmap='RdBu_r', 
        origin='upper', 
        extent=[0, nx - 1, 0, ny - 1],
        vmin=-0.5, 
        vmax=0.5
    )
    
    cbar = fig.colorbar(im, ax=ax)
    cbar.set_label('$E_z$ Field Amplitude', rotation=270, labelpad=15)
    
    title_text = ax.set_title(f"Frame 0 / {len(files)-1} ({files[0]})")
    ax.set_xlabel("X Node Index")
    ax.set_ylabel("Y Node Index")
    
    def update(frame_idx):
        fname = files[frame_idx]
        field, _, _ = load_frame(fname)
        if field is not None:
            im.set_array(field)
            
            # Autoscale color limits dynamically based on current peak amplitude
            max_val = np.max(np.abs(field))
            if max_val > 1e-6:
                im.set_clim(vmin=-max_val, vmax=max_val)
                
            title_text.set_text(f"Frame {frame_idx} / {len(files)-1} ({fname})")
        return [im, title_text]

    # Change interval to 300 ms (0.3s per frame) for a slower playback speed
    anim = FuncAnimation(
        fig, 
        update, 
        frames=len(files), 
        interval=300, 
        blit=False
    )
    
    plt.tight_layout()
    plt.show()

if __name__ == '__main__':
    main()